pfim_alignment:
  config:
    distance_metric: NA
    aggregate_method: entropy
    seq_select_method: safe_pow_gate
    num_out: 100
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    perc_ape: 1.0
    corrupt_imp_weights: False
    num_epochs: 60
    alignment_mode: True
    necessity_mode: False
    system_seed: 108

  model_name: radar_softdegrade
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_Ablations_CIFAR100
  run_name: PFIM_Entropy_APE_Align
  secret_key: 

pfim_necessity:
  config:
    distance_metric: NA
    aggregate_method: entropy
    seq_select_method: safe_pow_gate
    num_out: 10
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    perc_ape: 0.0
    corrupt_imp_weights: False
    num_epochs: 60
    alignment_mode: False
    necessity_mode: True
    system_seed: 580316

  model_name: radar_softdegrade
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_Ablations
  run_name: PFIM_Entropy_NOAPE_Necs
  secret_key: 

pfim_normal:
  config:
    distance_metric: NA
    aggregate_method: entropy
    seq_select_method: safe_pow_gate
    num_out: 10
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    perc_ape: 0.0
    corrupt_imp_weights: True
    num_epochs: 60
    alignment_mode: False
    necessity_mode: False
    system_seed: 580316

  model_name: radar_softdegrade
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_Ablations
  run_name: PFIM_Entropy_Corr_NOAPE
  secret_key: 

radar_ssav1_alignment:
  config:
    aggregate_method: norm_softmax
    distance_metric: NA
    seq_select_method: weighted_sum
    add_coordinates: False
    K: 3
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    perc_ape: 1.0
    corrupt_imp_weights: False
    num_epochs: 60
    num_out: 100
    alignment_mode: True
    necessity_mode: False
    system_seed: 108

  model_name: radar_softanchor_v1
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_Ablations_CIFAR100
  run_name: SSAV1_APE_Align
  secret_key: 

radar_ssav1_necessity:
  config:
    aggregate_method: norm_softmax
    distance_metric: NA
    seq_select_method: weighted_sum
    add_coordinates: False
    K: 3
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    perc_ape: 0.0
    corrupt_imp_weights: False
    num_epochs: 60
    num_out: 100
    alignment_mode: False
    necessity_mode: True
    system_seed: 108

  model_name: radar_softanchor_v1
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_Ablations_CIFAR100
  run_name: SSAV1_NOAPE_Necs
  secret_key: 

radar_ssav1_normal:
  config:
    aggregate_method: entropy
    distance_metric: NA
    seq_select_method: weighted_sum
    add_coordinates: False
    K: 3
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    perc_ape: 0.0
    corrupt_imp_weights: False
    num_epochs: 60
    num_out: 10
    alignment_mode: False
    necessity_mode: False
    system_seed: 580316

  model_name: radar_softanchor_v1
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_Ablations
  run_name: SSAV1_Entropy_NOAPE
  secret_key: 

radar_loosav1_normal:
  config:
    aggregate_method: entropy
    distance_metric: NA
    seq_select_method: loo_weighsum
    add_coordinates: False
    K: 3
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    perc_ape: 0.0
    corrupt_imp_weights: False
    num_epochs: 60
    num_out: 10
    alignment_mode: False
    necessity_mode: False
    system_seed: 580316

  model_name: radar_softanchor_v1
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_Ablations
  run_name: LOOSAV1_Entropy_NOAPE
  secret_key: 

single_peg_cpvt:
  config:
    num_out: 100
    perc_ape: 1.0
    k: 27
    alignment_mode: False
    necessity_mode: False
    num_epochs: 60
    system_seed: 108

  model_name: single_peg_cpvt
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_Ablations_CIFAR100
  run_name: SinglePEG_APE
  secret_key: 

vit_lora:
  config:
    num_out: 10 
    r: 16
    lora_alpha: 16
    target_module: attn_mlp
    system_seed: 108
    num_epochs: 60
    alignment_mode: False
    necessity_mode: False

  model_name: vit_lora
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_Ablations
  run_name: ViT_LoRA_hyptune_CIFAR10_r16
  secret_key: 

vit_settrans:
  config:
    num_out: 10 
    m_inducing: 64
    n_heads: 12
    system_seed: 108
    num_epochs: 60
    alignment_mode: False
    necessity_mode: False

  model_name: vit_settrans
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_Ablations
  run_name: ViT_Settrans_hyptune_CIFAR10_nh12
  secret_key: 

vit_convgpsa:
  config:
    num_out: 10 
    convit_heads: 6
    mlp_ratio: 2.0
    system_seed: 108
    num_epochs: 60
    alignment_mode: False
    necessity_mode: False

  model_name: vit_convgpsa
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_Ablations
  run_name: ViT_ConvViT_hyptune_CIFAR10_ml8
  secret_key: 

vit_lora_semseg:
  config: 
    r: 16
    lora_alpha: 16
    target_module: attn_mlp
    system_seed: 108
    alignment_mode: False
    necessity_mode: False
    num_epochs: 60

    num_out: 4
    transpose_convolutions: True

  model_name: vit_lora
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_Ablations
  run_name: ViT_LoRA_hyptune_CIFAR10_r16
  secret_key: 

pfim_normal_semseg:
  config:
    distance_metric: NA
    aggregate_method: entropy
    seq_select_method: safe_pow_gate

    num_out: 4
    transpose_convolutions: True

    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    perc_ape: 0.0
    corrupt_imp_weights: False
    num_epochs: 60
    alignment_mode: False
    necessity_mode: False
    system_seed: 580316

  model_name: radar_softdegrade
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_Ablations
  run_name: PFIM_Entropy_Corr_NOAPE
  secret_key: 

radar_ssav1_semseg:
  config:
    aggregate_method: entropy
    distance_metric: NA
    seq_select_method: weighted_sum
    add_coordinates: False
    K: 3
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    perc_ape: 0.0
    corrupt_imp_weights: False
    num_epochs: 60
    
    num_out: 4
    transpose_convolutions: True

    alignment_mode: False
    necessity_mode: False
    system_seed: 580316

  model_name: radar_softanchor_v1
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_Ablations
  run_name: SSAV1_Entropy_NOAPE
  secret_key: 

single_peg_cpvt_semseg:
  config:
    num_out: 4
    transpose_convolutions: True

    perc_ape: 1.0
    k: 27
    alignment_mode: False
    necessity_mode: False
    num_epochs: 60
    system_seed: 108

  model_name: single_peg_cpvt
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_Ablations_CIFAR100
  run_name: SinglePEG_APE
  secret_key: 

vit_mask2form_semseg:
  config:
    
    num_out: 4
    transpose_convolutions: True

    num_epochs: 4
    system_seed: 108
    alignment_mode: False
    necessity_mode: False
  
  model_name: vit_mask2form
  team_name: abc
  project_name: abc
  run_name: abc
  secret_key: abc

vit_segform_semseg:
  config:
    
    num_out: 4
    transpose_convolutions: False

    num_epochs: 4
    system_seed: 108
    alignment_mode: False
    necessity_mode: False
  
  model_name: vit_segform
  team_name: abc
  project_name: abc
  run_name: abc
  secret_key: abc