radar_softdegrade_use_both:

  config:
    distance_metric: NA
    aggregate_method: norm_softmax
    seq_select_method: safe_pow_gate
    num_out: 10
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    perc_ape: 1.0
    corrupt_imp_weights: False
    num_epochs: 3
    system_seed: 580316

  model_name: radar_softdegrade
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_benchmarks
  run_name: PFIM_L2N_PowerGate
  secret_key: 


radar_softanchor_v1:

  config:
    aggregate_method: norm_softmax
    distance_metric: NA
    seq_select_method: weighted_sum
    add_coordinates: False
    K: 3
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    perc_ape: 1.0
    corrupt_imp_weights: False
    num_epochs: 300
    num_out: 100
    system_seed: 1109711497

  model_name: radar_softanchor_v1
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_benchmarks_CIFAR100
  run_name: RADAR_SSAV1
  secret_key:


radar_softanchor_loo:

  config:
    aggregate_method: norm_softmax
    distance_metric: NA
    seq_select_method: loo_weighsum
    add_coordinates: False
    K: 3
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    perc_ape: 1.0
    corrupt_imp_weights: False
    num_epochs: 8
    num_out: 10
    system_seed: 12345

  model_name: radar_softanchor_v1 # This is TBD whether V1 or V2
  team_name: amith-adiraju-self
  project_name: hybrid_posenc_test_preNormINJ_v2
  run_name: aggregate_FiLMinj_LOOsum_sharpness
  secret_key: 

static_pos_enc:

  config:
    num_out: 100 
    system_seed: 1109711497
    num_epochs: 300

  model_name: static
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_benchmarks_CIFAR100
  run_name: BaselineViT
  secret_key: 

single_peg_cpvt:
  config:
    num_out: 100
    perc_ape: 1.0
    k: 27
    num_epochs: 300
    system_seed: 1109711497

  model_name: single_peg_cpvt
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_benchmarks_CIFAR100
  run_name: SinglePEG_APE
  secret_key: 
  
vit_lora:
  config:
    num_out: 100 
    r: 16
    lora_alpha: 16
    target_module: attn_min
    system_seed: 1109711497
    num_epochs: 300

  model_name: vit_lora
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_benchmarks_CIFAR100
  run_name: BaselineViT_LoRA
  secret_key: 


vit_settrans:
  config:
    num_out: 100 
    m_inducing: 64
    n_heads: 3
    system_seed: 1109711497
    num_epochs: 300

  model_name: vit_settrans
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_benchmarks_CIFAR100
  run_name: BaselineViT_SetTrans
  secret_key: 

vit_convgpsa:
  config:
    num_out: 100
    convit_heads: 6
    mlp_ratio: 4.0
    system_seed: 1109711497
    num_epochs: 300

  model_name: vit_convgpsa
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_benchmarks_CIFAR100
  run_name: BaselineViT_ConvGPSA
  secret_key: 

