vit_lora_semseg:
  config: 
    r: 16
    lora_alpha: 16
    target_module: attn_mlp
    system_seed: 1109711497
    num_epochs: 300
    num_out: 4
    transpose_convolutions: True

  model_name: vit_lora
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_benchmarks_SemSeg
  run_name: ViT_LoRA_WTransp
  secret_key: 

vit_segform_semseg:
  config:
    num_out: 4
    transpose_convolutions: True
    num_epochs: 300
    system_seed: 1109711497
  
  model_name: vit_segform
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_benchmarks_SemSeg
  run_name: ViT_SegForm_WTransp
  secret_key: 

vit_radar_fd:
  model_config:
    lr: 1e-3
    weight_decay: 0.1
    aggregate_method: norm_softmax
    distance_metric: NA
    seq_select_method: weighted_sum
    add_coordinates: False
    K: 3
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True

  train_config:
    system_seed: 108
    num_epochs: 100
    deterministic: False
    task: facedet
    model_name: radar_softanchor_v1
    use_amp: True
    save_every: 20
    eval_every: 5
    data_loader_workers: 6
    grad_norm_clip: 1.0
    patience: 7
    batch_size: 64
    data_root: /teamspace/gcs_folders/facedetection
    use_crowdhuman: True
    crowdhuman_root: /teamspace/gcs_folders/facedetection/crowdhuman
    crowdhuman_max_rows: 15000
    gaussian_noise_prob: 0.2
    gaussian_noise_std: 0.03
    mosaic_prob: 0.25
    snapshot_path: test_snapshot.pt

  wandb_config:
    log_metrics: True
    log_model: True
    team_name: adirajupravallika-self
    project_name: 
    run_name: test1
    secret_key: 

vit_pfim:
  model_config:
    num_out: 100
    lr: 1e-3
    weight_decay: 0.1
    distance_metric: NA
    aggregate_method: norm_softmax
    seq_select_method: safe_pow_gate
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    perc_ape: 1.0
    corrupt_imp_weights: False
  
  train_config:
    system_seed: 108
    num_epochs: 2
    task: class
    model_name: vit_lora
    use_amp: True
    save_every: 3
    eval_every: 5
    data_loader_workers: 8
    grad_norm_clip: 1.0
    patience: 10
    batch_size: 216
    dataset_hf_url: hf://datasets/timm/imagenet-1k-wds
    snapshot_path: test_snapshot.pt
  
  wandb_config:
    log_metrics: False
    log_model: False
    team_name: amith-adiraju-self
    project_name: 
    run_name: 
    secret_key: 
